export const columns = [
  { field: 'id', headerName: 'ID' },
  {
    field: 'subject',
    headerName: 'Subject',
  },
  {
    field: 'category',
    headerName: 'Category',
  },
  {
    field: 'date',
    headerName: 'Date & Time',
    type: 'number',
  },
  {
    field: 'recipients',
    headerName: 'Recipients',
    type: 'number',
  },
  {
    field: 'successRate',
    headerName: 'Success Rate',
    type: 'number',
  },
  {
    field: 'favorite',
    headerName: 'Favorite',
    type: 'number',
  },
  {
    field: 'actions',
    headerName: 'More',
  },
];

export const rows = [
  {
    id: 1,
    subject: 'School Closed Tomorrow',
    category: 'General',
    date: 'Nov 14, 2022',
    recipients: '274',
    successRate: '84%',
    favorite: true,
  },
  {
    id: 2,
    subject: 'Field Hockey Tryouts',
    category: 'Sports',
    date: 'Nov 14, 2022',
    recipients: '79',
    successRate: '61%',
    favorite: false,
  },
  {
    id: 3,
    subject: 'Field Trip Requirements',
    category: 'Fundraising',
    date: 'Nov 14, 2022',
    recipients: '14',
    successRate: '100%',
    favorite: false,
  },
  {
    id: 4,
    subject: 'Weekend Field Day',
    category: 'Menus',
    date: 'Nov 14, 2022',
    recipients: '381',
    successRate: '96%',
    favorite: true,
  },
  {
    id: 5,
    subject: 'Annual Excursion Plannings with...',
    category: 'Sports',
    date: 'Nov 14, 2022',
    recipients: '1322',
    successRate: '55%',
    favorite: true,
  },
  {
    id: 6,
    subject: 'Parents, Teachers Association...',
    category: 'School Closure',
    date: 'Nov 14, 2022',
    recipients: '475',
    successRate: '74%',
    favorite: false,
  },
  {
    id: 7,
    subject: 'Mid-Term Break for the Session',
    category: 'General',
    date: 'Nov 14, 2022',
    recipients: '200',
    successRate: '74%',
    favorite: false,
  },
];
